name: rollbar-yesod
version: 1.2.0
github: "stackbuilders/rollbar-haskell"
license: MIT
author: "Stack Builders Inc."
maintainer: "David Mazarro <dmunuera@stackbuilders.com>"
copyright: "2020-present Stack Builders Inc."
tested-with: GHC ==9.6.7, GHC ==9.8.4, GHC ==9.10.1

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
synopsis: >
  Provides error reporting capabilities to Yesod applications through Rollbar
  API.
category: Network
description: |
  Please see the README on GitHub at
  <https://github.com/stackbuilders/rollbar-haskell/tree/master/rollbar-yesod>

ghc-options:
  - -Wall

dependencies:
  - base >= 4.18 && < 5

flags:
  example:
    description: Build the example
    manual: false
    default: false

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

library:
  source-dirs: src
  dependencies:
    - rollbar-client >= 1.0 && < 2
    - rollbar-wai >= 1.0 && < 2
    - unliftio >= 0.2 && < 1
    - wai >= 3.2 && < 4
    - yesod-core >= 1.6 && < 2

executables:
  yesod-example:
    source-dirs: example
    main: Main.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - rollbar-client
      - rollbar-yesod
      - warp >= 3.3 && < 4
      - yesod-core
    when:
      - condition: flag(example)
        then:
          buildable: true
        else:
          buildable: false

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: *exe-ghc-options
    dependencies:
      - hspec >= 2.7 && < 3
      - rollbar-client
      - rollbar-yesod
      - yesod-core
      - yesod-test >= 1.6 && < 2
      - wai
    build-tools:
      - hspec-discover:hspec-discover >= 2.7 && < 3
