name: rollbar-client
version: 1.0.0
github: "stackbuilders/rollbar-haskell"
license: MIT
author: "Stack Builders Inc."
maintainer: "Sebastián Estrella <sestrella@stackbuilders.com>"
copyright: "2020 Stack Builders Inc."
tested-with: GHC ==8.8.4, GHC ==8.10.2

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: Core library to communicate with Rollbar API.
# category:            Web

description: |
  Please see the README on GitHub at
  <https://github.com/stackbuilders/rollbar-haskell/tree/master/rollbar-client>

ghc-options:
  - -Wall

dependencies:
  - base >= 4.13 && < 5

flags:
  example:
    description: Build the example
    manual: false
    default: false

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

library:
  source-dirs: src
  dependencies:
    - aeson >= 2.0 && <3
    - bytestring >= 0.10 && < 1
    - directory >= 1.3 && < 2
    - exceptions >= 0.10 && < 1
    - mtl >= 2.2 && < 3
    - process >= 1.6 && < 2
    - req >= 2.1 && < 4
    - text >= 1.2 && < 2
    - unordered-containers >= 0.2 && < 1
    - yaml >= 0.11 && < 1
  exposed-modules:
    - Rollbar.Client

executables:
  client-example:
    source-dirs: example
    main: Main.hs
    ghc-options: *exe-ghc-options
    dependencies:
      - rollbar-client
      - text
    when:
      - condition: flag(example)
        then:
          buildable: true
        else:
          buildable: false

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: *exe-ghc-options
    dependencies:
      - aeson
      - hspec >= 2.7 && < 3
      - mtl
      - rollbar-client
      - text
      - unordered-containers
      - yaml
    build-tools:
      - hspec-discover:hspec-discover >= 2.7 && < 3
