name: rollbar-client
version: 0.1.0
github: "stackbuilders/rollbar-haskell"
license: MIT
author: "Stack Builders Inc."
maintainer: "Sebastián Estrella <sestrella@stackbuilders.com>"
copyright: "2020 Stack Builders Inc."
tested-with: GHC ==8.6.5, GHC ==8.8.4, GHC ==8.10.2

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: Core library to communicate with Rollbar API.
# category:            Web

description: |
  Please see the README on GitHub at
  <https://github.com/stackbuilders/rollbar-haskell/tree/master/rollbar-client>

flags:
  example:
    description: Build the example
    manual: false
    default: false

dependencies:
  - base >= 4.12 && < 5

ghc-options:
  - -Wall

library:
  source-dirs: src
  dependencies:
    - aeson >= 1.4 && < 2
    - bytestring
    - directory
    - exceptions >= 0.10 && < 1
    - mtl >= 2.2 && < 3
    - process
    - req >= 2.1 && < 4
    - text
    - unordered-containers
    - yaml >= 0.11 && < 1
  exposed-modules:
    - Rollbar.Client

executables:
  client-example:
    source-dirs: example
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - rollbar-client
    when:
      - condition: flag(example)
        then:
          buildable: true
        else:
          buildable: false

tests:
  hlint:
    main: Main.hs
    source-dirs: test/hlint
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - hlint

  hspec:
    main: Spec.hs
    source-dirs: test/hspec
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aeson
      - hspec >= 2.7 && < 3
      - mtl
      - rollbar-client
      - text
      - unordered-containers
      - yaml
    build-tools:
      - hspec-discover:hspec-discover >= 2.7 && < 3
