---
version: 2.1

commands:
  cabal_build:
    parameters:
      ghc:
        type: string

    steps:
      - run: apt update
      - run: apt install -y ca-certificates coreutils git gnupg zlib1g-dev
      - run: apt-key adv --keyserver keyserver.ubuntu.com --recv-keys BA3CBA3FFE22B574
      - run: echo 'deb http://downloads.haskell.org/debian buster main' > /etc/apt/sources.list.d/haskell.list
      - run: apt update
      - run: apt install -y cabal-install-3.2 ghc-<< parameters.ghc >>
      - run: echo 'export PATH=/opt/ghc/bin:$PATH' >> $BASH_ENV
      - run: sha256sum */*.cabal > checksum.txt
      - restore_cache:
          keys:
            - v1-cabal-<< parameters.ghc >>-{{ checksum "checksum.txt" }}
            - v1-cabal-<< parameters.ghc >>-
      - run: cabal update
      - run: cabal configure --enable-tests -fexample
      - run: cabal build all --jobs=1 --only-dependencies
      - run: cabal build all --jobs=1
      - save_cache:
          key: v1-cabal-<< parameters.ghc >>-{{ checksum "checksum.txt" }}
          paths:
            - dist-newstyle
            - ~/.cabal/packages
            - ~/.cabal/store
      - run: cabal test all

  stack_build:
    parameters:
      resolver:
        type: string

    steps:
      - run: apt update
      - run: apt install -y coreutils
      - run: sha256sum */package.yaml > checksum.txt
      - restore_cache:
          keys:
            - v1-stack-<< parameters.resolver >>-{{ checksum "stack-<< parameters.resolver >>.yaml.lock" }}-{{ checksum "checksum.txt" }}
            - v1-stack-<< parameters.resolver >>-{{ checksum "stack-<< parameters.resolver >>.yaml.lock" }}-
            - v1-stack-<< parameters.resolver >>-
      - run: stack update
      - run: stack build --no-terminal --jobs=1 --only-dependencies --test
      - run: stack build --no-terminal --jobs=1 --test --no-run-tests --pedantic
      - save_cache:
          key: v1-stack-<< parameters.resolver >>-{{ checksum "stack-<< parameters.resolver >>.yaml.lock" }}-{{ checksum "checksum.txt" }}
          paths:
            - .stack-work
            - rollbar-cli/.stack-work
            - rollbar-client/.stack-work
            - rollbar-wai/.stack-work
            - rollbar-yesod/.stack-work
            - ~/.stack
      - run: stack test --no-terminal

jobs:
  cabal_8_10:
    docker:
      - image: debian:10

    steps:
      - checkout
      - cabal_build:
          ghc: "8.10.2"

  cabal_8_8:
    docker:
      - image: debian:10

    steps:
      - checkout
      - cabal_build:
          ghc: "8.8.4"

  cabal_8_6:
    docker:
      - image: debian:10

    steps:
      - checkout
      - cabal_build:
          ghc: "8.6.5"

  stack_16:
    docker:
      - image: fpco/stack-build-small:lts-16.17
        environment:
          STACK_YAML: stack-16.yaml

    steps:
      - checkout
      - stack_build:
          resolver: "16"

  stack_14:
    docker:
      - image: fpco/stack-build-small:lts-14.27
        environment:
          STACK_YAML: stack-14.yaml

    steps:
      - checkout
      - stack_build:
          resolver: "14"

workflows:
  main:
    jobs:
      - cabal_8_10
      - cabal_8_8
      - cabal_8_6
      - stack_16
      - stack_14
