name: rollbar-cli
version: 1.2.0
github: "stackbuilders/rollbar-haskell"
license: MIT
author: "Stack Builders Inc."
maintainer: "David Mazarro <dmunuera@stackbuilders.com>"
copyright: "2020-present Stack Builders Inc."
tested-with: GHC ==9.6.7, GHC ==9.8.4, GHC ==9.10.1

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: Simple CLI tool to perform commons tasks such as tracking deploys.
category: Network

description: |
  Please see the README on GitHub at
  <https://github.com/stackbuilders/rollbar-haskell/tree/master/rollbar-cli>

ghc-options:
  - -Wall

dependencies:
  - base >= 4.18 && < 5

_exe-ghc-options: &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

library:
  source-dirs: src
  dependencies:
    - optparse-applicative >= 0.14 && < 1
    - rollbar-client >= 1.0 && < 2

executables:
  rollbar:
    main: Main.hs
    source-dirs: app
    ghc-options: *exe-ghc-options
    dependencies:
      - rollbar-cli
      - rollbar-client

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    ghc-options: *exe-ghc-options
    dependencies:
      - rollbar-cli
